# Generated by Django 4.2.3 on 2023-07-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_factory', '0002_translation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='language',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='service',
            name='details',
        ),
        migrations.RemoveField(
            model_name='softskill',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SoftSkill',
        ),
    ]
