# Generated by Django 4.2.3 on 2023-07-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_factory', '0003_delete_education_delete_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='to',
            field=models.CharField(default='eng', max_length=10),
            preserve_default=False,
        ),
    ]
